# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Requires a valid GITHUB_TOKEN
# --build-arg GITHUB_TOKEN=xxxx

# Runs goreleaser in Boring Crypto Go container in order to allow
# goreleaser to build a valid Boring Crypto binary

FROM golang:1.25-bookworm@sha256:7af46e70d2017aef0b4ce2422afbcf39af0511a61993103e948b61011233ec42

ARG GITHUB_TOKEN
ARG VERSION

RUN curl -L https://github.com/goreleaser/goreleaser/releases/download/v2.7.0/goreleaser_Linux_x86_64.tar.gz | tar -xz -C /usr/local/bin/ goreleaser

WORKDIR /app
ADD . .

# Native FIPS 140-3 environment variables
ENV CGO_ENABLED=1
ENV GOFIPS140=latest
ENV GODEBUG=fips140=on

RUN go mod download
RUN go mod tidy

RUN GITHUB_TOKEN=$GITHUB_TOKEN 
GORELEASER_CURRENT_TAG=$VERSION goreleaser release --clean