# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Requires a valid GITHUB_TOKEN
# --build-arg GITHUB_TOKEN=xxxx

# Runs goreleaser in Boring Crypto Go container in order to allow
# goreleaser to build a valid Boring Crypto binary

FROM goboring/golang:1.16.1b7

ARG GITHUB_TOKEN
ARG VERSION

RUN go install github.com/goreleaser/goreleaser@latest

WORKDIR /app
ADD . .

RUN go mod download
RUN go mod tidy
RUN GITHUB_TOKEN=$GITHUB_TOKEN GORELEASER_CURRENT_TAG=$VERSION goreleaser release --rm-dist