# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Runs goreleaser to build linux version using Boring Crypto
# Expects env: GITHUB_TOKEN

# use following to build without Boring Crypto:
# --build-arg CGO_ENABLED=0
# --build-arg GO_CONTAINER=golang:1.14

ARG GO_CONTAINER=goboring/golang:1.14.4b4
FROM ${GO_CONTAINER}

ARG CGO_ENABLED=1

RUN curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh

WORKDIR /app
ADD . .

ENV CGO_ENABLED=$CGO_ENABLED
RUN go mod download
RUN goreleaser release --rm-dist
# RUN goreleaser release --snapshot --rm-dist