# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: apigee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus
      automountServiceAccountToken: false
      tolerations:
      - key: "prometheus"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - image: docker.io/prom/prometheus
        imagePullPolicy: IfNotPresent
        name: prometheus
        ports:
        - containerPort: 9090
        args:
        - --config.file=/etc/prometheus/prometheus.yaml
        - --storage.tsdb.path=/data
        - --storage.tsdb.retention.time=12h
        volumeMounts:
        - mountPath: /etc/prometheus
          name: config-volume
          readOnly: true
        - mountPath: /data
          name: data-volume
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: sa-token
      volumes:
      - name: config-volume
        configMap:
          name: prometheus-config
      - name: data-volume
        emptyDir: {}
      - name: sa-token
        secret:
          defaultMode: 420
          secretName: prometheus-token
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: apigee
  labels:
    app: prometheus
spec:
  ports:
  - name: http
    port: 9090
    targetPort: 9090
  selector:
    app: prometheus